<a href="https://colab.research.google.com/github/victornator25/Data-Science/blob/main/Ejercicio3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

A=np.arange(1,65).reshape(8,8)
B=np.arange(0.40, 0.80, 0.01).reshape(8,5)


In [6]:
A

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [7]:
B

array([[0.4 , 0.41, 0.42, 0.43, 0.44],
       [0.45, 0.46, 0.47, 0.48, 0.49],
       [0.5 , 0.51, 0.52, 0.53, 0.54],
       [0.55, 0.56, 0.57, 0.58, 0.59],
       [0.6 , 0.61, 0.62, 0.63, 0.64],
       [0.65, 0.66, 0.67, 0.68, 0.69],
       [0.7 , 0.71, 0.72, 0.73, 0.74],
       [0.75, 0.76, 0.77, 0.78, 0.79]])

In [9]:
#para unir las matrices 
AB=np.concatenate((A,B), axis = 1)
AB.shape
AB 


array([[ 1.  ,  2.  ,  3.  ,  4.  ,  5.  ,  6.  ,  7.  ,  8.  ,  0.4 ,
         0.41,  0.42,  0.43,  0.44],
       [ 9.  , 10.  , 11.  , 12.  , 13.  , 14.  , 15.  , 16.  ,  0.45,
         0.46,  0.47,  0.48,  0.49],
       [17.  , 18.  , 19.  , 20.  , 21.  , 22.  , 23.  , 24.  ,  0.5 ,
         0.51,  0.52,  0.53,  0.54],
       [25.  , 26.  , 27.  , 28.  , 29.  , 30.  , 31.  , 32.  ,  0.55,
         0.56,  0.57,  0.58,  0.59],
       [33.  , 34.  , 35.  , 36.  , 37.  , 38.  , 39.  , 40.  ,  0.6 ,
         0.61,  0.62,  0.63,  0.64],
       [41.  , 42.  , 43.  , 44.  , 45.  , 46.  , 47.  , 48.  ,  0.65,
         0.66,  0.67,  0.68,  0.69],
       [49.  , 50.  , 51.  , 52.  , 53.  , 54.  , 55.  , 56.  ,  0.7 ,
         0.71,  0.72,  0.73,  0.74],
       [57.  , 58.  , 59.  , 60.  , 61.  , 62.  , 63.  , 64.  ,  0.75,
         0.76,  0.77,  0.78,  0.79]])

In [11]:
#Unir con la media a una matriz
C = np.append(AB,[np.mean(AB, axis=0)], axis= 0)
C.shape
C

array([[ 1.   ,  2.   ,  3.   ,  4.   ,  5.   ,  6.   ,  7.   ,  8.   ,
         0.4  ,  0.41 ,  0.42 ,  0.43 ,  0.44 ],
       [ 9.   , 10.   , 11.   , 12.   , 13.   , 14.   , 15.   , 16.   ,
         0.45 ,  0.46 ,  0.47 ,  0.48 ,  0.49 ],
       [17.   , 18.   , 19.   , 20.   , 21.   , 22.   , 23.   , 24.   ,
         0.5  ,  0.51 ,  0.52 ,  0.53 ,  0.54 ],
       [25.   , 26.   , 27.   , 28.   , 29.   , 30.   , 31.   , 32.   ,
         0.55 ,  0.56 ,  0.57 ,  0.58 ,  0.59 ],
       [33.   , 34.   , 35.   , 36.   , 37.   , 38.   , 39.   , 40.   ,
         0.6  ,  0.61 ,  0.62 ,  0.63 ,  0.64 ],
       [41.   , 42.   , 43.   , 44.   , 45.   , 46.   , 47.   , 48.   ,
         0.65 ,  0.66 ,  0.67 ,  0.68 ,  0.69 ],
       [49.   , 50.   , 51.   , 52.   , 53.   , 54.   , 55.   , 56.   ,
         0.7  ,  0.71 ,  0.72 ,  0.73 ,  0.74 ],
       [57.   , 58.   , 59.   , 60.   , 61.   , 62.   , 63.   , 64.   ,
         0.75 ,  0.76 ,  0.77 ,  0.78 ,  0.79 ],
       [29.   , 30.   , 31.   , 

In [13]:
# Parte 4. Agregar una columna al final con el valor maximo de cada fila
D = np.max(C, axis=1)
data = np.concatenate((C,D[:,None]), axis = 1)
print(data.shape)


# Parte 5. Guardar el archivo 
np.savetxt('datos.txt', data, delimiter=',', fmt='%.3f')

(9, 14)


In [14]:
# Lectura de los datos
data_read = np.loadtxt("datos.txt", delimiter=",")
data_read

array([[ 1.   ,  2.   ,  3.   ,  4.   ,  5.   ,  6.   ,  7.   ,  8.   ,
         0.4  ,  0.41 ,  0.42 ,  0.43 ,  0.44 ,  8.   ],
       [ 9.   , 10.   , 11.   , 12.   , 13.   , 14.   , 15.   , 16.   ,
         0.45 ,  0.46 ,  0.47 ,  0.48 ,  0.49 , 16.   ],
       [17.   , 18.   , 19.   , 20.   , 21.   , 22.   , 23.   , 24.   ,
         0.5  ,  0.51 ,  0.52 ,  0.53 ,  0.54 , 24.   ],
       [25.   , 26.   , 27.   , 28.   , 29.   , 30.   , 31.   , 32.   ,
         0.55 ,  0.56 ,  0.57 ,  0.58 ,  0.59 , 32.   ],
       [33.   , 34.   , 35.   , 36.   , 37.   , 38.   , 39.   , 40.   ,
         0.6  ,  0.61 ,  0.62 ,  0.63 ,  0.64 , 40.   ],
       [41.   , 42.   , 43.   , 44.   , 45.   , 46.   , 47.   , 48.   ,
         0.65 ,  0.66 ,  0.67 ,  0.68 ,  0.69 , 48.   ],
       [49.   , 50.   , 51.   , 52.   , 53.   , 54.   , 55.   , 56.   ,
         0.7  ,  0.71 ,  0.72 ,  0.73 ,  0.74 , 56.   ],
       [57.   , 58.   , 59.   , 60.   , 61.   , 62.   , 63.   , 64.   ,
         0.75 ,  0.76 ,  